### ISSUE TITLE
add complete working example for non-R users

### ISSUE THREAD

**Issue by titaniumbones** [eeholmes/CoV19#1]
Hey it's probably just me but if you cna add a complete file somehwere nder say ~/example~ then I cna maybe use this to gneerate a bunc hof images for use in a web dashboard.  thx Eli.

**Comment by eeholmes** [comment]
Hey Matt! Start with the README.Rmd file. That shows the code that made the figures. I'll put up a better example of figures later. But the readme Rmd file at least shows the code that made the figures in the readme.

**Comment by eeholmes** [comment]
I need to figure out how to run the data update automatically. Right now I have to run the the functions manually on my machine and then upload to GitHub.

**Comment by titaniumbones** [comment]
I'll fork and add the actions on a pr

On Mar. 23, 2020 1:46 p.m., Eli Holmes <notifications@github.com> wrote:

I need to figure out how to run the data update automatically. Right now I have to run the the functions manually on my machine and then upload to GitHub.

**Comment by titaniumbones** [comment]
closing this.
